
name: Publish NPM Package

on:
  push:
    branches:
      - bicocca

env:
  NODE_ENV: "production"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 4.1.8
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@gnosischain'

      - run: npm install
      - run: npm run build
      - run: npm publish
        working-directory: packages/gasless-wallet
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}